services:
  discord-recorder:
    build: .
    container_name: discord-recorder
    env_file:
      - .env
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN:?Set DISCORD_TOKEN in .env}
      RECORDINGS_DIR: /app/recordings
      SESSION_PREFIX: ${SESSION_PREFIX:-session}
    volumes:
      - ${RECORDINGS_DIR:-./recordings}:/app/recordings
    restart: unless-stopped

  transcriber:
    image: python:3.11-slim
    container_name: discord-transcriber
    working_dir: /app
    env_file:
      - .env
    environment:
      RECORDINGS_DIR: /app/recordings
      OUTPUT_DIR: /app/out
      WHISPER_MODEL: ${WHISPER_MODEL:-}
      WHISPER_DEVICE: ${WHISPER_DEVICE:-}
      WHISPER_COMPUTE: ${WHISPER_COMPUTE:-}
      WHISPER_SEGMENT_BEAM: ${WHISPER_SEGMENT_BEAM:-}
      WHISPER_LANG: ${WHISPER_LANG:-}
      WHISPER_VAD: ${WHISPER_VAD:-}
      SANITIZE_LOWER_NOISE: ${SANITIZE_LOWER_NOISE:-}
    volumes:
      - ./:/app
      - ${RECORDINGS_DIR:-./recordings}:/app/recordings
      - ${OUTPUT_DIR:-./out}:/app/out
    command: >-
      bash -lc "pip install --no-cache-dir faster-whisper && python transcribe.py"
    restart: "no"
