name: CI

on:
  push:
    branches: ["main", "master", "work", "codex/**"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Ruff (lint)
        run: ruff check .
      - name: Mypy (type check)
        run: mypy --config-file pyproject.toml
      - name: Pytest
        env:
          PYTHONPATH: .
        run: pytest
